# Site settings
title: Legal Malware Labs
email: kyle@legalmalware.com
description: > # this means to ignore newlines until "baseurl:"
  Legal Malware Labs researches and developes the latest Red Team & Penetration Testing Tools
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://legalmalware.com" # the base hostname & protocol for your site
github_username:  circleswerun

# Build settings
markdown: kramdown
